title: averichev
markdown: kramdown
theme: minima
collections:
  articles:
    output: true
    permalink: /articles/:name/
defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: post
