title: averichev
markdown: kramdown
theme: minima
slugify_mode: latin
collections:
  articles:
    output: true
defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: post
